// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// OpenSocket provides a mock function with given fields: hostname, port, network
func (_m *Repository) OpenSocket(hostname string, port int, network string, payload []byte) (bool, time.Duration, error) {
	ret := _m.Called(hostname, port, network, payload)

	if len(ret) == 0 {
		panic("no return value specified for OpenSocket")
	}

	var r0 bool
	var r1 time.Duration
	var r2 error
	if rf, ok := ret.Get(0).(func(string, int, string, []byte) (bool, time.Duration, error)); ok {
		return rf(hostname, port, network, payload)
	}
	if rf, ok := ret.Get(0).(func(string, int, string, []byte) bool); ok {
		r0 = rf(hostname, port, network, payload)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if rf, ok := ret.Get(1).(func(string, int, string, []byte) time.Duration); ok {
		r1 = rf(hostname, port, network, payload)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(time.Duration)
		}
	}
	if rf, ok := ret.Get(2).(func(string, int, string, []byte) error); ok {
		r2 = rf(hostname, port, network, payload)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
