// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
    mock.Mock
}

// Lookup provides a mock function with given fields: recordType, name
func (_m *Repository) Lookup(recordType string, name string) ([]string, error) {
    ret := _m.Called(recordType, name)

    if len(ret) == 0 {
        panic("no return value specified for Lookup")
    }

    var r0 []string
    if rf, ok := ret.Get(0).(func(string, string) []string); ok {
        r0 = rf(recordType, name)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).([]string)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(string, string) error); ok {
        r1 = rf(recordType, name)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

func NewRepository(t interface {
    mock.TestingT
    Cleanup(func())
}) *Repository {
    mock := &Repository{}
    mock.Mock.Test(t)

    t.Cleanup(func() { mock.AssertExpectations(t) })

    return mock
}
