// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	api "github.com/monitoror/monitoror/monitorables/ssl/api"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FetchCertificate provides a mock function with given fields: hostname, port
func (_m *Repository) FetchCertificate(hostname string, port int) (*api.Certificate, error) {
	ret := _m.Called(hostname, port)

	if len(ret) == 0 {
		panic("no return value specified for FetchCertificate")
	}

	var r0 *api.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*api.Certificate, error)); ok {
		return rf(hostname, port)
	}
	if rf, ok := ret.Get(0).(func(string, int) *api.Certificate); ok {
		r0 = rf(hostname, port)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(hostname, port)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
