// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Exec provides a mock function with given fields: command
func (_m *Repository) Exec(command string) (string, int, time.Duration, error) {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 string
	var r1 int
	var r2 time.Duration
	var r3 error
	if rf, ok := ret.Get(0).(func(string) (string, int, time.Duration, error)); ok {
		return rf(command)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(string)
		}
	}
	if rf, ok := ret.Get(1).(func(string) int); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Get(1).(int)
	}
	if rf, ok := ret.Get(2).(func(string) time.Duration); ok {
		r2 = rf(command)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(time.Duration)
		}
	}
	if rf, ok := ret.Get(3).(func(string) error); ok {
		r3 = rf(command)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
